---

- local_action: stat path="{{ app_templates_path }}/config/{{ app.key }}"
  become: no
  register: cfg

- name: setup app config files
  become: yes
  template:
    src: "{{ item }}"
    dest: "{{ app.value.deploy_path }}/config/"
  when: cfg.stat.isdir is defined and cfg.stat.isdir
  with_fileglob:
      - "{{ cfg.stat.path }}/*"
      - "{{ cfg.stat.path }}/.*"

- local_action: stat path="{{ app_templates_path }}/webroot/{{ app.key }}"
  become: no
  register: www  

- name: setup webroot files
  become: yes
  template:
    src: "{{ item }}"
    dest: "{{ app.value.deploy_path }}/webroot/"
  when: www.stat.isdir is defined and www.stat.isdir
  with_fileglob:
    - "{{ www.stat.path }}/*"
    - "{{ www.stat.path }}/.*"
