---
- name: run core migrations
  become: yes
  become_user: "{{ app_deploy_user }}"
  command: "bin/cake migrations migrate -p BEdita/Core"
  args:
    chdir: "{{ item.value.deploy_path }}"
  run_once: true
  when: item.value.migrations is defined
  with_dict: "{{ apps }}"
  tags:
    - bedita-migrations

# TEMP solution: should work iterating over {{ apps }} - TBD
- name: run plugins migrations
  become: yes
  become_user: "{{ app_deploy_user }}"
  command: "bin/cake migrations migrate -p {{ item.name }}"
  args:
    chdir: "{{ apps.get(item.path).get('deploy_path') }}"
  when: item.path in apps
  with_items: 
    - name: OpenCorporation
      path: opencorporation_api
    - name: Doorway
      path: doorway_api
    - name: DockBooking
      path: dockbooking_api
  run_once: true
  tags:
    - bedita-migrations

- name: seed api keys
  become: yes
  become_user: "{{ app_user }}"
  command: "bin/cake migrations seed -p BEdita/Core --seed ApplicationFromEnvSeed"
  args:
    chdir: "{{ apps.get(item.value.path).get('deploy_path') }}"
  environment:
    BEDITA_API_KEY: "{{ item.value.api_key }}" 
    BEDITA_APP_NAME: "{{ item.value.name }}"
  run_once: true
  when: item.value.path in apps
  with_dict: "{{ api_keys }}"
  tags:
    - bedita
    - bedita-setup

- name: seed admin credentials
  become: yes
  become_user: "{{ app_user }}"
  command: "bin/cake migrations seed -p BEdita/Core --seed AdminFromEnvSeed"
  args:
    chdir: "{{ apps.get(item.key).get('deploy_path') }}"
  environment:
    BEDITA_ADMIN_USR: "{{ item.value.admin_usr }}" 
    BEDITA_ADMIN_PWD: "{{ item.value.admin_pwd }}" 
  run_once: true
  when: item.value.admin_usr is defined and item.value.admin_pwd is defined 
  with_dict: "{{ apps_secrets }}"
  tags:
    - bedita
    - bedita-setup
